services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"

  books:
    build: ./BooksService
    container_name: books
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    expose:
      - "5000"

  loans_major:
    build: ./LoansService
    container_name: loans_major
    ports:
      - "5002:5001"
    depends_on:
      - mongo
      - books

  loans_minor:
    build: ./LoansService
    container_name: loans_minor
    ports:
      - "5003:5001"
    depends_on:
      - mongo
      - books

  nginx:
      image: nginx
      container_name: nginx-proxy
      ports:
        - "80:8000"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - books
        - loans_major
        - loans_minor
      restart: always
